### ISSUE TITLE
Unable to add module extention

### ISSUE THREAD

**Issue by akhileshgandhi** [OfficeDev/Outlook-Add-in-JavaScript-ModuleExtension#9]
Hi,

I have tried every possible way to add ModuleExtention with no success. Visual Studio Project with not allow to update Manifest and Deploy.
If I try updating manifest in O365 it throws ever with manifest.
please advice how I can overcome this issue. I have spend more then a week with all possible ways to run this project in my environment with no success.

There is no additional help available,how to make module extension work.

**Comment by chbighammsft** [comment]
Akhilesh,

A couple of things that you can start with:

Did you create the project using an Outlook Add-in template in Visual Studio? Unfortunately, those won’t work because VS doesn’t support module extensions yet. You’ll need to start with an empty template and add files to it. The Billable Hours sample is a good place to start to find the files that you’ll need to create.

Does the Billable Hours sample work? If so, I suggest that you start with the manifest file from the sample and modify it for your project. Getting the manifest right is the trickiest part of creating an extension, as you are no doubt aware.

Make sure that you are using the right version of Office. You need to be using the version that you install from Office 365. If you click File -> Office Account you’ll see product information. You need to be using Office 365 Pro Plus; the important part is where it says “Subscription product.”

And finally, make sure that you have the right build of Outlook. You should be using version 16.0.6200.1000 or higher.

I hope that this helps,
Chuck

**Comment by akhileshgandhi** [comment]
Chuck,

thanks a lot for your guidance. It worked :) .

One last question, is it possible to share access token between outlook and
DynamicCRM. What I am looking to do is fetch Data from Dynamic CRM without
asking user to provide login information again.

Regards,
Akhilesh Gandhi

## 

Best Regards,

Akhilesh Gandhi

CTO, MoreYeahs https://mail.google.com/

M +91 769-205-0888

Join Me on : Site http://www.moreyeahs.com/ | Blog
https://akhileshgandhi.wordpress.com/| Linkedin
https://akhileshgandhi.wordpress.com/ | @MoreyeahsInc
https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2ftwitter.com%2fMoreyeahsInc&data=01%7c01%7crick.melgar%40microsoft.com%7cc85ca8a702814e4f0f1108d2fb45c260%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=0pRUxW%2fKKOnC%2fymIa3dz8d3nxrnrZYlNK9gXyDZ9Zuc%3d

**Comment by chbighammsft** [comment]
Take a look at this topic:  https://dev.office.com/docs/add-ins/outlook/authentication
Chuck
